### PR TITLE
Bug fix: Married status in US

### LINKED ISSUE #813: Married toggle doesn't save in PE US, preventing users from providing info on spouse
Steps to repro:
1. Visit [PolicyEngine US Household page](https://policyengine.org/us/household)
2. Switch from `Single` to `Married`
3. Go to one of the `People` menus, e.g. `Income`
4. Return to the `Household` > `People` menu

In (3), there's no drop-down to provide info for the spouse. In (4), it shows up as `Single` instead of `Married`.

This similarly occurs if adding dependents: there's a drop-down to enter information about the head and dependents, but not the spouse.

This works correctly in PE UK. I think it worked correctly in the US within the past week or two, but I'm not sure.

### PR DESCRIPTION
**Pull request by mwufi**
### Steps to test

1. Visit [PolicyEngine US Household page](https://policyengine.org/us/household)
2. Switch from Single to Married
3. Go to one of the People menus, e.g. Income
4. Return to the Household > People menu

### Issues fixed

fixes #813

### CODE REVIEW

File: policyengine-client/src/countries/us/us.jsx [hunk 1]
```diff
@@ -690,9 +690,9 @@ export class US extends Country {
 
     setHouseholdMaritalStatus(status) {
         let situation = this.situation;
-        if (status === "Married" & !situation.people.includes("Your spouse")) {
+        if (status === "Married" & !situation.people.hasOwnProperty("Your spouse")) {
```
Comment (nikhilwoodruff) [inline policyengine-client/src/countries/us/us.jsx:693]: Thanks for making a start on this @mwufi! I just realised the true cause of the bug: bracket application on these two lines (the first condition should be bracketed on its own). Hope you don't mind my editing the PR and merging.

```suggestion
        if ((status === "Married") & !situation.people.includes("Your spouse")) {
```
