### PR TITLE
UI fixes

### LINKED ISSUE #383: Unify SPM unit and household tabs on household page

### LINKED ISSUE #441: Add disclaimer to `Your results` household pages
For example, https://entitledto.co.uk states:
>Our estimate is based on the information you have entered and does not guarantee entitlement. It uses 2021/22 benefit and tax rates.

How about this?
>PolicyEngine's tax and benefit estimates are not official. Please consult a tax adviser and/or your local human services agency.

### LINKED ISSUE #501: Change `Calculate the UK impact` button to `Calculate UK impact`
Also `Return to the UK impact` -> `Return to UK impact`

### PR DESCRIPTION
**Pull request by nikhilwoodruff**
Fixes #441 
Fixes #501 
Fixes #383 

## Screenshots

Default view:
image
Expanded (similar for UK but with different link):
image

### CODE REVIEW

File: policyengine-client/src/policyengine/pages/household/accountingTable.jsx [hunk 1]
```diff
@@ -7,6 +8,19 @@ import Spinner from "../../general/spinner";
...
 import { getTranslators } from "../../tools/translation";
 
+const { Panel } = Collapse;
+
+function HouseholdResultsCaveats() {
+    const country = useContext(CountryContext);
+	return (
+		<Collapse style={{marginTop: 15}} defaultActiveKey={["0"]} ghost>
+			<Panel header={<><ExclamationCircleOutlined />  &nbsp; &nbsp;Disclaimer</>} key="1">
+				<p>{`Results are calculated using the OpenFisca-${country.properName} tax-benefit microsimulation model, may not constitute exact tax liabilities or benefit entitlements. See the `}<a href={`https://github.com/PolicyEngine/OpenFisca-${country.properName}`}>repository</a> for more information.</p>
```
Comment (MaxGhenis) [inline policyengine-client/src/policyengine/pages/household/accountingTable.jsx:18]: I don't think we need to get technical here. Could you also default it to uncollapsed? It's important that users see this.
```suggestion
				<p>{`PolicyEngine results may not constitute exact tax liabilities or benefit entitlements.</p>
```

**Review by MaxGhenis — APPROVED** [review]
